## **Question 1 (b)**

In [59]:
import numpy as np

# input signal
Inp = np.array([[2, 3], [4, 5]])
print('Input Matrix : ', Inp.shape)
print(Inp,"\n")

 # filter 
Kernel = np.array([[1, 2], [2, 1]])
print('Kernel: ',Kernel.shape)
print(Kernel)

Input Matrix :  (2, 2)
[[2 3]
 [4 5]] 

Kernel:  (2, 2)
[[1 2]
 [2 1]]


In [60]:
# number columns and rows of the input 
Inp_row, Inp_col = Inp.shape 

# number of columns and rows of the filter
Ker_row, Ker_col = Kernel.shape

#  calculate the output dimensions
output_row = Inp_row + Ker_row - 1
output_col = Inp_col + Ker_col - 1
print('Output:', output_row, output_col)


Output: 3 3


In [65]:
def pad_with(mat, pad_width, iaxis, kwargs):
  padding = kwargs.get('padder', 0)
  mat[:pad_width[0]] = padding
  mat[-pad_width[1]:] = padding
  return mat

Inp = np.pad(Inp, 1, pad_with)
print("Input after padding: \n" , Inp)

Input after padding: 
 [[0 0 0 0]
 [0 2 3 0]
 [0 4 5 0]
 [0 0 0 0]]


In [67]:
# O = [[0 for j in range(3) for i in range(3)]]
O = [ [0]*3 for i in range(3)]
O = np.array(O)
print(len(O),len(O[0]))
for i in range(len(Inp)-1):
  for j in range(len(Inp[0])-1):
    for x in range(len(Kernel)):
      for y in range(len(Kernel[0])):
        O[i][j] += Kernel[x][y]*Inp[i+x][j+y]
        
print("\n Output Matrix: \n", O)        

3 3

 Output Matrix: 
 [[ 2  7  6]
 [ 8 21 13]
 [ 8 14  5]]


## **Question 3 (b)**

In [0]:
def compute_tr(Tr, Hr, prob_r, r):
  temp = 0
  for i in range(0,len(r)):
    temp += prob_r[i]
    Tr[i] = (len(r)-1)*temp
    Hr[i] = round(Tr[i])
  return Tr,Hr


In [79]:
r = [0,1,2,3]
prob_r = [0.8,0.2,0,0]

Tr = [0 for i in range(len(r))]
Hr = [0 for i in range(len(r))]

compute_tr(Tr,Hr,prob_r,r)

print("Tr = ",Tr)
print("Hr = ",Hr)


Tr =  [2.4000000000000004, 3.0, 3.0, 3.0]
Hr =  [2, 3, 3, 3]


In [81]:
z = [0,1,2,3]
prob_z = [0,0.3,0.7,0]
Gz = [0 for i in range(len(z))]
Sk = [0 for i in range(len(z))]

compute_tr(Gz,Sk,prob_z,z)

print("Gz = ",Gz)
print("Sk = ",Sk)

Gz =  [0, 0.8999999999999999, 3.0, 3.0]
Sk =  [0, 1, 3, 3]


In [97]:
#Mapping 
Map = [0 for i in range(len(r))]

for i in range(0,len(r)):
  minn = 1000
  for j in range(len(z)-1,-1,-1):
    if(abs(Hr[i] - Sk[j]) <= minn):
      minn = abs(Hr[i]-Sk[j])
      Map[i] = j
print(Map)

[1, 2, 2, 2]
